# Pytorch - Tensor Basics

In [1]:
import torch
import numpy as np

### Tensor shape and size

#### Empty tensor

In [13]:
x = torch.empty(0)
x

tensor([])

In [15]:
x.shape, x.size() # it it seems that shape & size() returns the same thing

(torch.Size([0]), torch.Size([0]))

#### 1-D Tensors

In [54]:
x = torch.empty(1) # the initial values are close to zero
x

tensor([-3.2221e-24])

In [55]:
x.item() # this can be used only if there is just one element in the tensor

-3.2221055228188436e-24

In [52]:
x = torch.empty(2)
x

tensor([-3.2221e-24,  4.5612e-41])

In [8]:
x.shape, x.size()

(torch.Size([2]), torch.Size([2]))

#### 2-D Tensors

In [9]:
torch.empty(2,2)

tensor([[-3.2221e-24,  4.5612e-41],
        [-3.2221e-24,  4.5612e-41]])

In [10]:
x = torch.empty(3,3)
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 7.2288e-27, 3.0733e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [11]:
x.shape, x.size()

(torch.Size([3, 3]), torch.Size([3, 3]))

#### 3-D Tensors

In [25]:
x = torch.empty(3,3,2)
x

tensor([[[-2.2404e+28,  4.5656e-41],
         [-2.2404e+28,  4.5656e-41],
         [-2.2405e+28,  4.5656e-41]],

        [[-2.2405e+28,  4.5656e-41],
         [-2.2405e+28,  4.5656e-41],
         [-2.2405e+28,  4.5656e-41]],

        [[-2.2405e+28,  4.5656e-41],
         [-2.2406e+28,  4.5656e-41],
         [-2.2406e+28,  4.5656e-41]]])

In [26]:
x.shape

torch.Size([3, 3, 2])

### Tensor initialisation

In [16]:
torch.empty(2, 2)

tensor([[-3.2221e-24,  4.5612e-41],
        [-3.2221e-24,  4.5612e-41]])

In [17]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [18]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [25]:
torch.rand(3, 3) # random from [0, 1]

tensor([[0.0294, 0.6452, 0.9954],
        [0.7846, 0.7190, 0.8035],
        [0.0901, 0.3813, 0.5536]])

In [26]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [28]:
torch.tensor([[1, 2], [3, 4]])

tensor([[1, 2],
        [3, 4]])

#### Init from __numpy__ array

In [2]:
np_x = np.ones(5)
np_x

array([1., 1., 1., 1., 1.])

In [10]:
x = torch.from_numpy(np_x) # IMPORTANT! - x keeps reference to np_x (the data is not copied) assuming the tensor is on CPU (can be different on GPU)
x

tensor([4., 4., 4., 4., 4.], dtype=torch.float64)

In [11]:
x.add_(1) # underscode means the operation is done in place
x, np_x # both x and np_x was modified

(tensor([5., 5., 5., 5., 5.], dtype=torch.float64),
 array([5., 5., 5., 5., 5.]))

### Tensor on device

In [19]:
device_cuda = torch.device("cuda")
device_cuda

device(type='cuda')

In [20]:
device_cpu = torch.device("cpu")
device_cpu

device(type='cpu')

#### Define tensor on the specific device

In [21]:
x = torch.ones(5, device=device_cpu) # this won't always work for cuda (cuda must be enabled)
x

tensor([1., 1., 1., 1., 1.])

#### Move a tensor to a device

In [22]:
x.to(device_cpu) # for cuda, CUDA must be defined and enabled
x

tensor([1., 1., 1., 1., 1.])

### Tensor data types

### Operations on Tensors

In [32]:
x = torch.tensor([[1, 2], [1, 2]])
y = torch.tensor([[3,3], [5, 5]])
x, y

(tensor([[1, 2],
         [1, 2]]),
 tensor([[3, 3],
         [5, 5]]))

#### Adding tesors (corresponding elements ared added to each other)

In [34]:
z = x + y
z

tensor([[4, 5],
        [6, 7]])

In [44]:
z = x.add(y)
z

tensor([[4, 5],
        [6, 7]])

In [46]:
z = x + 1 # add single value to each element
z

tensor([[2, 3],
        [2, 3]])

In [49]:
z = x + torch.tensor([1, 2]) # add by rows
z

tensor([[2, 4],
        [2, 4]])

In [51]:
 # add by rows TODO

#### Multiplication 

In [39]:
z = x * y
z

tensor([[ 3,  6],
        [ 5, 10]])

In [42]:
z = x.mul(y)
z

tensor([[ 3,  6],
        [ 5, 10]])

In [41]:
z = x.multiply(y)
z

tensor([[ 3,  6],
        [ 5, 10]])

#### Division

In [38]:
z = x / y
z

tensor([[0.3333, 0.6667],
        [0.2000, 0.4000]])

In [43]:
z = x.div(y)
z

tensor([[0.3333, 0.6667],
        [0.2000, 0.4000]])

### Tensor reshaping

In [56]:
x = torch.ones(4, 4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [60]:
torch.reshape(x, (16,)) # the second arg must be a tuple

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [62]:
x.view(8,2) # reshaping by using view method

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [64]:
x.view(-1, 2, 2) # -1 means that the last dimention should be calculated based on the the given ones

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])