# Numpy - Element Access

In [2]:
import numpy as np

In [4]:
a = np.array([[10, 20, 30], [40, 50, 60]])

In [6]:
x1 = a[0][0] # the same approach as for python list
x1

10

In [9]:
x1 = a[0, 0] # this is an alternate way (it won't work for a list)
x1

10

In [12]:
col = a[:, 1] # get the whole second column
col

array([20, 50])

In [14]:
row = a[1, :] # get the whole row
row

array([40, 50, 60])

In [15]:
b = np.array([0, 1 , 2, 3, 4, 5, 6, 7, 8, 9])
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b[0:9:3] # [start_index(inclusive):end_index(exclusive), step]

array([0, 3, 6])

In [17]:
for frame in a:
    print(f'FRAME:{frame}')

FRAME:[10 20 30]
FRAME:[40 50 60]
