# Numpy - Quick Array Init

In [2]:
import numpy as np

### Zeros

In [4]:
zeros = np.zeros((2,5,3)) # initialize 2x5x3 matrix of 0s
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### Ones

In [26]:
ones = np.ones((4,4))   # init with 1.0 (floating point number)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Full

In [27]:
full = np.full((4,4), 5) # init with number (int32 by default)
full

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [28]:
full = np.full((4,4), 9, dtype='float32') # init with float number
full

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]], dtype=float32)

### FullLike

In [22]:
full_like = np.full_like(full, 0)   # tworzy tablicę o takim samym rozmiarze i typie danych
full_like

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

### Identity

In [25]:
identity = np.identity(5, dtype='int32')
identity

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)