# Numpy - Basic Operations

In [2]:
import numpy as np

In [23]:
a = [1, 2, 3]
b = [10, 20, 30]
c= [[10, 20, 30], [40, 50, 60]]

### Basic operations on arrays (to compare)

In [24]:
x = a + b
x

[1, 2, 3, 10, 20, 30]

In [25]:
x = a + c
x

[1, 2, 3, [10, 20, 30], [40, 50, 60]]

In [26]:
x = a * 2
x

[1, 2, 3, 1, 2, 3]

In [27]:
x = c * 2
x

[[10, 20, 30], [40, 50, 60], [10, 20, 30], [40, 50, 60]]

### Basic operations on np.array 

In [30]:
na = np.array(a)
nb = np.array(b)
nc = np.array(c)

In [45]:
na + nb # add element-by-element

array([11, 22, 33])

In [46]:
np.add(na, nb)

array([11, 22, 33])

In [37]:
na + 10 # add int value to each element

array([11, 12, 13])

In [38]:
na * 2 # multiply each element

array([2, 4, 6])

In [43]:
na + nc # add elem-by-elem in the last left-side dimention

array([[11, 22, 33],
       [41, 52, 63]])

In [47]:
na * nb

array([10, 40, 90])

In [49]:
np.multiply(na, nb)

array([10, 40, 90])

In [62]:
nc.shape

(2, 3)

### Transpose

In [58]:
nc.T.shape

(3, 2)

In [60]:
na, na.shape

(array([1, 2, 3]), (3,))

In [71]:
na.T, na.T.shape # for one-dim array transpose opperation does not change anything

(array([1, 2, 3]), (3,))

### Reshape

In [74]:
nc

array([[10, 20, 30],
       [40, 50, 60]])

In [76]:
nc.shape

(2, 3)

In [81]:
nc_reshaped = nc.reshape(3, 2) # it does not change the original arrays
nc_reshaped  

array([[10, 20],
       [30, 40],
       [50, 60]])

In [84]:
nc.T # transpose does not work the same way as reshape(3,2)

array([[10, 40],
       [20, 50],
       [30, 60]])

In [86]:
nc[0, 0] = 1

In [87]:
nc

array([[ 1, 20, 30],
       [40, 50, 60]])

In [91]:
nc_reshaped # IMPORTANT - nc_reshaped is not a separate instnce of nc (it's only a kind of a view of the original array)

array([[ 1, 20],
       [30, 40],
       [50, 60]])

In [93]:
nc_reshaped = np.reshape(nc, (1,6))
nc_reshaped

array([[ 1, 20, 30, 40, 50, 60]])

In [95]:
nc_reshaped = np.reshape(nc, (1,-1)) # minus at the latest positions means the value is inferred from the earlier once
nc_reshaped

array([[ 1, 20, 30, 40, 50, 60]])

In [97]:
nc_reshaped = np.reshape(nc, (3,-1))
nc_reshaped

array([[ 1, 20],
       [30, 40],
       [50, 60]])

In [98]:
nc_reshaped = np.reshape(nc, (6,-1))
nc_reshaped

array([[ 1],
       [20],
       [30],
       [40],
       [50],
       [60]])

### Conditional operation

In [99]:
x = na > 1
x

array([False,  True,  True])

In [103]:
nc >= 30

array([[False, False,  True],
       [ True,  True,  True]])

In [104]:
np.where(nc>=30) # returns the indexes of True value as a tuple

(array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [70]:
x = np.where(na > 1, 1, -1) # Synatax: np.where(condition, value if true, value if false)
x

array([-1,  1,  1])

### IsIn

In [101]:
a = np.array([1 ,3, 5, 6, 7, 8, 5, 2, 6])
x = (5,6,7)
mask = np.isin(a, x)
mask

array([False, False,  True,  True,  True, False,  True, False,  True])