# Numpy - Random

In [2]:
import numpy as np

In [3]:
r1 = np.random.rand(5) 
r1

array([0.73103817, 0.75769354, 0.89150343, 0.63178204, 0.50219495])

In [4]:
r2 = np.random.rand(2, 2)
r2

array([[0.12072664, 0.84579316],
       [0.42474602, 0.42803488]])

In [5]:
r3 = np.random.rand(2, 3, 2)
r3

array([[[0.58728934, 0.91092597],
        [0.80824948, 0.41326213],
        [0.08253326, 0.57849882]],

       [[0.65221558, 0.04199827],
        [0.5182924 , 0.02740379],
        [0.96796282, 0.57839273]]])

FRAME:[[0.58728934 0.91092597]
 [0.80824948 0.41326213]
 [0.08253326 0.57849882]]
FRAME:[[0.65221558 0.04199827]
 [0.5182924  0.02740379]
 [0.96796282 0.57839273]]
